### ISSUE TITLE
Tips on how to run github workflow checks for stacked diffs?

### ISSUE THREAD

**Issue by opqpop** [getcord/spr#161]
We have a github workflow like this, which runs fine on my 1st diff, but when i have stacked diffs, the 2nd and 3rd ones don't run

I'm not entirely sure why, any thoughts on best way for them to run on all diffs?

Is it because I have `branches: ["main"]`?

.github/workflows/project.yml file

```
name: Project

on:
  pull_request:
    branches: ["main"]
    paths:
      - "src/project/**"
      - ".github/workflows/project.yml"
  push:
    branches: ["main"]
    paths:
      - "src/project/**"
      - ".github/workflows/project.yml"

jobs:
  verify-frontend:
```
